mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('shopapp.urls')),
    path('req/', include('requestdataapp.urls')),
]

requestdataapp/urls.py
from django.urls import path

from .views import process_get_view, user_form, handle_file_upload


app_name = "requestdataapp"


urlpatterns = [
    path("get/", process_get_view, name= "get-view"),
    path("bio/",user_form, name="user-form"),
    path("upload/",handle_file_upload, name="file-upload"),
]

shopapp/urls.py
from django.urls import path
app_name = "shopapp"
from .views import shop_index, groups_list, products_list, orders_list, create_product, create_order

urlpatterns = [
    path("", shop_index, name="index"),
    path("groups/", groups_list, name="groups_list"),
    path("products/", products_list, name="products_list"),
    path("products/create/", create_product, name="product_create"),
    path("orders/", orders_list, name="orders_list"),
    path("orders/create/",create_order, name= "order_create")
]

requestdataapp/models.py
from django.db import models

# Create your models here.

shopapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class Products(models.Model):
    # class Meta:
    #     ordering = ["name", "price"]

    name = models.CharField(max_length=30)
    description = models.TextField(null=False, blank=True)
    price = models.DecimalField(default=0, max_digits=8, decimal_places=2)
    discount = models.SmallIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    archived = models.BooleanField(default=False)

    # @property
    # def description_short(self):
    #     if len(self.description)<48:
    #         return self.description
    #     return self.description[:48]+"..."

    def __str__(self):
        return f"Products(pk={self.pk},name={self.name!r})" # как ссылки


class Order(models.Model):
    # class Meta:
    #     ordering = ["user", "products"]
    delivery_address = models.TextField(null=True, blank=True)
    promocode = models.CharField(max_length=16, null=False, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    products = models.ManyToManyField(Products, related_name="orders")

requestdataapp/forms.py
from django import forms
from django.core.exceptions import  ValidationError
from django.core.files.uploadedfile import InMemoryUploadedFile

class UserBioForm(forms.Form):
    name = forms.CharField(max_length=40)
    id = forms.IntegerField(label="Age", min_value=14, max_value=60)
    bio = forms.CharField(label="Biography",widget=forms.Textarea)

def validate_file_name(file:InMemoryUploadedFile) -> None:
    if file.name and "virus" in file.name and "Gitlab" in file.name:
        raise ValidationError("поменяй пож. имя файла без 'virus's")

class UploadFileForm(forms.Form):
    file = forms.FileField(validators=[validate_file_name])

shopapp/forms.py
from django import forms
from django.core import validators
from .models import Products, Order


class ProductForm(forms.ModelForm):
    class Meta:
        model = Products
        fields = "name","price","description","discount"

class OrderForms(forms.ModelForm):
    class Meta:
        model = Order
        fields = "user","products","products","delivery_address"

requestdataapp/views.py
from django.core.files.storage import FileSystemStorage
from django.db.models.expressions import result
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.core.files.storage import FileSystemStorage

from .forms import UserBioForm, UploadFileForm

def process_get_view(request: HttpRequest) -> HttpResponse:
    a = request.GET.get("a", "")
    b = request.GET.get("b", "")
    result = a + b
    context ={
        "a" : a,
        "b" : b,
        "result" : result,
    }
    return render(request,"requestdataapp/request-query-params.html",context= context)

def user_form(request: HttpRequest) -> HttpResponse:
    context = {
        "form": UserBioForm(),

    }
    return render(request, "requestdataapp/user-bio-form.html", context=context)

def handle_file_upload(request: HttpRequest) -> HttpResponse:
    if request.method == "POST":
        form = UploadFileForm(request.POST,request.FILES)
        if form.is_valid():
            # myfile = request.FILES["myfile"]
            myfile = form.cleaned_data["file"]
            fs = FileSystemStorage()
            filename = fs.save(myfile.name, myfile)
            print("saved file", filename)
    else:
        form = UploadFileForm()
    context = {
        "form": form,
    }
    return render(request, "requestdataapp/file-upload.html", context= context)

shopapp/views.py
from django.contrib.auth.models import Group
from timeit import default_timer

from django.http import HttpResponse, HttpRequest
from django.shortcuts import render, redirect, reverse

from .models import Products, Order
from .forms import ProductForm, OrderForms


# Create your views here.
def shop_index(request: HttpRequest):
    products = [
        ('Laptop', 1999),
        ('Desktop', 2999),
        ('Smartphone', 999),

    ]
    context = {
        "time_running": default_timer(),
        "products": products,
    }
    return render(request, 'shopapp/shop-index.html', context=context)

def groups_list(request: HttpRequest):
    context = {
        "groups": Group.objects.prefetch_related('permissions').all()
    }
    return render(request, 'shopapp/groups-list.html', context=context)

def products_list(request: HttpRequest):
    context = {
        "products": Products.objects.all()
    }
    return render(request, 'shopapp/products-list.html', context=context)

def create_product(request: HttpRequest) -> HttpResponse:
    if request.method == "POST":
        form = ProductForm(request.POST)
        if form.is_valid():
            # name = form.cleaned_data["name"]
            # price = form.cleaned_data["price"]
            # Products.objects.create(**form.cleaned_data)
            form.save()
            url = reverse("shopapp:products_list")
            return redirect(url)
    else:
        form = ProductForm()
    context = {
        "form": form,
    }
    return render(request,'shopapp/create-product.html', context=context)
def create_order(request:HttpRequest) -> HttpResponse:
    if request.method == "POST":
        form = OrderForms(request.POST)
        if form.is_valid():
            form.save()
            url = reverse("shopapp:orders_list")
            return redirect(url)
    else:
        form = OrderForms()
    context = {
        "form": form,
    }
    return render(request,'shopapp/create-order.html',context=context)


def orders_list(request: HttpRequest):
    context = {
        "orders": Order.objects.select_related("user").prefetch_related("products").all()
    }
    return render(request, 'shopapp/order_list.html', context=context)

requestdataapp/templates/requestdataapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}

        {% endblock %}
    </title>
</head>
<body>
  {% block body %}

  {% endblock %}

<br>

<div>

<!--    HTTP User - Agent {{request.user_agent}}-->
</div>
</body>
</html>

requestdataapp/templates/requestdataapp/file-upload.html
{% extends 'requestdataapp/base.html' %}


{% block title %}
    File upload
{% endblock %}


{% block body %}
    <h1>Upload file</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}

        <button type="submit">Upload</button>
    </form>
{% endblock %}

requestdataapp/templates/requestdataapp/request-query-params.html
{% extends 'requestdataapp/base.html' %}



{% block title %}
 Demo request params
{% endblock %}


{% block body %}
    <h1>Good afternooon {% firstof request.GET.name 'User'%}</h1>

    <div>
        <pre>
            a = '{{a}}'
            b = '{{b}}'
            result = '{{result}}'
        </pre>
    </div>
{% endblock %}

requestdataapp/templates/requestdataapp/user-bio-form.html
{% extends 'requestdataapp/base.html' %}

{% block title %}
    User BIO
{% endblock %}

{% block body %}
    <h1>User form</h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{form.as_p}}


            <button type="submit">
                Submit
            </button>
        </form>
    </div>
    {% if request.POST %}
        <div>
            <h2>Previous form data:</h2>
            <table>
                <tr>
                    <td>Full name:</td>
                    <td>{{request.POST.name}}</td>
                </tr>
                <tr>
                    <td>Age:</td>
                    <td>{{request.POST.age}}</td>
                </tr>
                <tr>
                    <td>Bio:</td>
                    <td>
                        <p>{{request.POST.bio|linebreaks}}</p>
                    </td>
                </tr>
            </table>
        </div>
    {% endif %}
{% endblock %}

shopapp/templates/shopapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <title>
        {% block title %}
            Base Title
        {% endblock %}
    </title>

</head>
<body>
    {% block body %}
        Base body
    {% endblock %}


</body>
</html>

shopapp/templates/shopapp/create-order.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Создать заказ
{% endblock %}

{% block body %}
  <h1> Создать новый заказ </h1>
  <div>

    <form method="post">
      {% csrf_token %}

      {{ form.as_p }}

      <button type="submit">
        Создать заказ
      </button>
    </form>
  </div>
  <div>
    <a href="{% url 'shopapp:orders_list' %}">
        Back to order list
    </a>
  </div>
{% endblock %}

shopapp/templates/shopapp/create-product.html
{% extends 'shopapp/base.html' %}

{% block title %}
  Create Product
{% endblock %}

{% block body %}
  <h1>Create a new product</h1>
<div>
  <form method="post">
    {% csrf_token %}

    {{form.as_p}}

    <button type="submit">
      Create
    </button>
  </form>
</div>
<div>
    <a href="{% url 'shopapp:products_list' %}">
        Back to products list
    </a>
</div>
{% endblock %}

shopapp/templates/shopapp/groups-list.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Groups List
{% endblock %}

{% block body %}
    <h1>Groups</h1>
    <div>
    {% if not groups %}
    <h3>No groups yet</h3>

    {% else %}
    <ul>
    {% for group in groups %}
        <li>
            <div>{{ group.name }}</div>
            <ul>
                {% for permission in group.permissions.all %}
                <li>
                    {{ permission.name }}
                    (<code>{{ permission.codename }}</code>)
                </li>

                {% endfor %}
            </ul>
        </li>
        {% endfor%}
    </ul>
{% endif %}
    </div>
{% endblock %}

shopapp/templates/shopapp/orders-list.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Orders List
{% endblock %}

{% block body %}
    {% if orders %}
        <div>
            <h1>Orders</h1>
            {% for order in orders %}
                <p>Order by {% firstof order.user.first_name order.user.username %}</p>
                <p>Promocode: <code>{{ order.promocode }}</code></p>
                <p>Delivery address: {{ order.delivery_address }}</p>
                <div>
                    Products in order:
                    <ul>
                        {% for product in order.products.all %}
                            <li>{{ product.name }} for ${{ product.price }}</li>
                        {% endfor %}

                    </ul>
                </div>
            {% endfor %}
        </div>
    {% else %}
        <h3>No orders yet</h3>
    {% endif %}
    <div>
        <a href="{% url 'shopapp:order_create' %}">
            Creat a new order
        </a>
    </div>
{% endblock %}

shopapp/templates/shopapp/products-list.html
{% extends 'shopapp/base.html' %}

{% block title %}
    Products list
{% endblock %}

{% block body %}
    {% if products %}
        <div>
            <h1>Products:</h1>
            {% for product in products %}
                <div>
                    <p>Name: {{ product.name }}</p>
                    <p>Price: {{ product.price }}</p>
                    <p>Discount: {% firstof product.discount 'no discount' %}</p>
                </div>
            {% endfor %}
        </div>

    {% else %}
        <h3>No products yet</h3>
    {% endif %}

    <div>
        <a href="{% url 'shopapp:product_create' %}">
            Creat a new product
        </a>
    </div>

{% endblock %}

shopapp/templates/shopapp/shop-index.html
{% extends 'shopapp/base.html'%}
{% block title %}
    Shop Index
{% endblock %}

{% block body %}
    <h1>Hello Shop Index</h1>
    <div>
        <ul>
            {% for name, price in products %}
                <li>{{ name }} ({{ name|length }}) for ${{ price }}</li>
                <span>Lucky product {{ name|capfirst }}</span>
                {% empty %}
                No products here
            {% endfor %}
        </ul>
    </div>

{% endblock %}